require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'



platform :ios, '10.0'

target 'FlowQountPertamina' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'SwiftyJSON', '5.0'      
  
  pod 'Charts', '3.3.0'  
  

  pod 'react-native-pinch-new', :path => '../node_modules/react-native-pinch-new'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  target 'FlowQountPertaminaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  
post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'FlowQountPertamina-tvOS' do
  # Pods for FlowQountPertamina-tvOS

  target 'FlowQountPertamina-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
